language: python
python:
  - '3.6.9'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis
  - MOZ_HEADLESS=1

script:
  - ./manage.py test

addons:
  firefox: latest
  # apt:
  #   packages:
  #     firefox-geckodriver

before_install:
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver
 - geckodriver --version
 - export MOZ_HEADLESS=1
