language: python
python:
  - '3.6.9'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt
  # - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis
  # - MOZ_HEADLESS=1

script:
  - ./manage.py test

addons:
  firefox: latest
  # apt:
  #   packages:
  #     firefox-geckodriver
